[package]
name = "recipnps"
version = "0.1.0"
edition = "2021"
authors = ["Jingnan Shi <jnshi@mit.edu>"]

[dependencies]
nalgebra = "0.29"
roots = "0.0.7"

[lib]
name = "recipnps"
path = "src/lib.rs"
